//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCAMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoE_PaperGenerate
    {
        public int SL { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> AcaCalId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public string Type { get; set; }
        public string UserLoginId { get; set; }
        public string UserIP { get; set; }
        public string PageName { get; set; }
        public string EventName { get; set; }
        public string MessageType { get; set; }
        public string Message { get; set; }
        public string StudentRoll { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string PageId { get; set; }
        public string PageUrl { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedLoginId { get; set; }
        public string ApprovedIP { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string DownloaderLoginId { get; set; }
        public string DownloadIP { get; set; }
        public Nullable<bool> IsDownloaded { get; set; }
    }
}
