//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCAMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionHistory
    {
        public int CollectionHistoryId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> BillHistoryMasterId { get; set; }
        public Nullable<int> BillHistoryId { get; set; }
        public string MoneyReciptSerialNo { get; set; }
        public Nullable<int> AcaCalId { get; set; }
        public Nullable<int> TypeDefinitionId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> CounterId { get; set; }
        public string BankName { get; set; }
        public string ChequeNo { get; set; }
        public string ReferenceNo { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string TransactionCode { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
