//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCAMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentACUDetail
    {
        public int StdACUDetailID { get; set; }
        public int StdAcademicCalenderID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> StatusTypeID { get; set; }
        public Nullable<int> SchSetUpID { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> CGPA { get; set; }
        public Nullable<decimal> GPA { get; set; }
        public Nullable<decimal> TranscriptCredit { get; set; }
        public Nullable<decimal> TranscriptCGPA { get; set; }
        public Nullable<decimal> TranscriptGPA { get; set; }
        public Nullable<bool> IsAllGradeSubmitted { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TotalGradePoint { get; set; }
    }
}
